[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && ./node_modules/.bin/tsc"

[deploy]
startCommand = "node dist/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
