[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "node dist/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
