[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cp -r .next/static .next/standalone/.next/static && (test -d public && cp -r public .next/standalone/public || true)"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
